routes/web.php
<?php

use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeController;
use App\Models\Company;
use App\Models\Employee;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome');

// companies routes
Route::get('companies/listing', [CompanyController::class, 'listing'])->name('get-companies');
Route::resource('companies', CompanyController::class);


// employee routes
Route::get('employees/listing', [EmployeeController::class, 'listing'])->name('get-employees');
Route::resource('employees', EmployeeController::class);


Route::model('company', Company::class);
Route::model('employee', Employee::class);

app/Models/Company.php
<?php

namespace App\Models;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;


class Company extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [ 'name', 'type', 'website','description' ];

    public function employees(): HasMany
    {
        return $this->hasMany(Employee::class, 'company_id', 'id');
    }
}

app/Models/Employee.php
<?php

namespace App\Models;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;


class Employee extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [ 'first_name', 'last_name', 'email_address','position', 'city', 'country', 'status', 'company_id' ];


    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class)->withTrashed();
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Company\SaveRequest;
use App\Models\Company;
use Illuminate\Contracts\View\View;
use Illuminate\Http\JsonResponse;
use Yajra\DataTables\Facades\DataTables;

class CompanyController extends Controller
{
    /**
     * @return View
     */
    public function index(): View
    {
        return view('companies.index');
    }

    public function listing(){
        return DataTables::of(Company::query())
            ->addColumn('Actions', function($data) {
                return '<button type="button" class="btn btn-success btn-sm" id="getEditCompanyData" data-id="'.$data->id.'">Edit</button>
                    <button type="button" data-id="'.$data->id.'" data-toggle="modal" data-target="#DeleteCompanyModal" class="btn btn-danger btn-sm" id="getDeleteId">Delete</button>';
            })
            ->rawColumns(['Actions'])
            ->make(true);
    }

    /**
     * @param SaveRequest $request
     * @return JsonResponse
     */
    public function store(SaveRequest $request): JsonResponse
    {
        $company = Company::create($request->all());
        return Response()->json(['data' => $company, 'success' => true]);
    }

    /**
     * @param Company $company
     * @return JsonResponse
     */
    public function edit(Company $company): JsonResponse
    {
        $html = view('companies.edit', compact('company'))->render();
        return response()->json(['html' => $html, 'success' => true]);
    }

    /**
     * @param SaveRequest $request
     * @param Company $company
     * @return JsonResponse
     */
    public function update(SaveRequest $request, Company $company): JsonResponse
    {
        $company->update($request->all());
        return Response()->json(['data' => $company->fresh(), 'success' => true]);
    }

    /**
     * @param Company $company
     * @return JsonResponse
     */
    public function destroy(Company $company): JsonResponse
    {
        $company->delete();
        return Response()->json(['success' => true]);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Employee\SaveRequest;
use App\Models\Company;
use App\Models\Employee;
use Illuminate\Contracts\View\View;
use Illuminate\Http\JsonResponse;
use Yajra\DataTables\Facades\DataTables;

class EmployeeController extends Controller
{
    /**
     * @return View
     */
    public function index(): View
    {
        $companies = Company::select(['id', 'name'])->get();
        return view('employees.index', compact('companies'));
    }

    public function listing(){
        return DataTables::of(Employee::with('company:id,name'))
            ->addColumn('Actions', function($data) {
                return '<button type="button" class="btn btn-success btn-sm" id="getEditEmployeeData" data-id="'.$data->id.'">Edit</button>
                    <button type="button" data-id="'.$data->id.'" data-toggle="modal" data-target="#DeleteEmployeeModal" class="btn btn-danger btn-sm" id="getDeleteId">Delete</button>';
            })
            ->rawColumns(['Actions'])
            ->make(true);
    }

    /**
     * @param SaveRequest $request
     * @return JsonResponse
     */
    public function store(SaveRequest $request): JsonResponse
    {
        $employee = Employee::create($request->all());
        return Response()->json(['data' => $employee, 'success' => true]);
    }

    /**
     * @param Employee $employee
     * @return JsonResponse
     */
    public function edit(Employee $employee): JsonResponse
    {
        $companies = Company::select(['id', 'name'])->get();
        $html = view('employees.edit', compact('employee', 'companies'))->render();
        return response()->json(['html' => $html, 'success' => true]);
    }

    /**
     * @param SaveRequest $request
     * @param Employee $employee
     * @return JsonResponse
     */
    public function update(SaveRequest $request, Employee $employee): JsonResponse
    {
        $employee->update($request->all());
        return Response()->json(['data' => $employee->fresh(), 'success' => true]);
    }

    /**
     * @param Employee $employee
     * @return JsonResponse
     */
    public function destroy(Employee $employee): JsonResponse
    {
        $employee->delete();
        return Response()->json(['success' => true]);
    }
}

resources/views/companies/edit.blade.php
<div class="form-group">
    <label for="Name">Name*:</label>
    <input type="text" class="form-control" name="name" id="editName" value="{{$company->name}}">
</div>
<div class="form-group">
    <label for="Name">Type*:</label>
    <select class="form-control" name="type" id="editType">
        <option value="Public Limited Company" {{ $company->type == 'Public Limited Company' ? 'selected' : '' }}>Public Limited Company</option>
        <option value="Private Limited Company" {{ $company->type == 'Private Limited Company' ? 'selected' : '' }}>Private Limited Company</option>
        <option value="Registered Company" {{ $company->type == 'Registered Company' ? 'selected' : '' }}>Registered Company</option>
    </select>
</div>

<div class="form-group">
    <label for="Name">Website*:</label>
    <input type="url" class="form-control" name="website" id="editWebsite" value="{{$company->website}}">
</div>

<div class="form-group">
    <label for="Name">Description:</label>
    <textarea class="form-control" name="description" id="editDescription">{{$company->description}}</textarea>
</div>

resources/views/companies/index.blade.php
@extends('layouts.app')



@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Companies
                        <button style="float: right; font-weight: 900;" class="btn btn-info btn-sm" type="button"
                                data-toggle="modal" data-target="#CreateCompanyModal">
                            Create Company
                        </button>
                    </div>

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered datatable">
                                <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Name</th>
                                    <th>Type</th>
                                    <th>Website</th>
                                    <th>Description</th>
                                    <th width="150" class="text-center">Action</th>
                                </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal" id="CreateCompanyModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Company Create</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <!-- Modal body -->
                <div class="modal-body">
                    <div class="alert alert-danger alert-dismissible fade show" role="alert" style="display: none;">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="alert alert-success alert-dismissible fade show" role="alert" style="display: none;">
                        <strong>Success!</strong>Company was added successfully.
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="form-group">
                        <label for="Name">Name*:</label>
                        <input type="text" class="form-control" name="name" id="name">
                    </div>
                    <div class="form-group">
                        <label for="Name">Type*:</label>
                        <select class="form-control" name="type" id="type">
                            <option value="Public Limited Company">Public Limited Company</option>
                            <option value="Private Limited Company">Private Limited Company</option>
                            <option value="Registered Company">Registered Company</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="Name">Website*:</label>
                        <input type="url" class="form-control" name="website" id="website">
                    </div>
                    <div class="form-group">
                        <label for="Name">Description:</label>
                        <textarea class="form-control" name="description" id="description"></textarea>
                    </div>
                </div>
                <!-- Modal footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-success" id="SubmitCompanyForm">Create</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Edit Company Modal -->
    <div class="modal" id="EditCompanyModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Edit</h4>
                    <button type="button" class="close modelClose" data-dismiss="modal">&times;</button>
                </div>
                <!-- Modal body -->
                <div class="modal-body">
                    <div class="alert edit-alert-danger alert-dismissible fade show" role="alert"
                         style="display: none;">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="alert alert-success alert-dismissible fade show" role="alert" style="display: none;">
                        <strong>Success!</strong>Updated.
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div id="EditCompanyModalBody">

                    </div>
                </div>
                <!-- Modal footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-success" id="SubmitEditCompanyForm">Update</button>
                    <button type="button" class="btn btn-danger modelClose" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Delete Company Modal -->
    <div class="modal" id="DeleteCompanyModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Delete Company</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <!-- Modal body -->
                <div class="modal-body">
                    <p>Are you sure want to delete this company?</p>
                </div>
                <!-- Modal footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" id="SubmitDeleteCompanyForm">Yes</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                </div>
            </div>
        </div>
    </div>
    <!-- end bootstrap model -->

@endsection

@section('script')
    <script type="text/javascript">
        $(document).ready(function () {
            // init datatable.
            let dataTable = $('.datatable').DataTable({
                processing: true,
                serverSide: true,
                autoWidth: false,
                pageLength: 25,
                // scrollX: true,
                "order": [[0, "desc"]],
                ajax: '{{ route('get-companies') }}',
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'name', name: 'name'},
                    {data: 'type', name: 'type'},
                    {data: 'website', name: 'website'},
                    {data: 'description', name: 'description'},
                    {data: 'Actions', name: 'Actions', orderable: false, serachable: false, sClass: 'text-center'},
                ]
            });

            // Create Company Ajax request.
            $('#SubmitCompanyForm').click(function (e) {
                e.preventDefault();
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                $.ajax({
                    url: "{{ route('companies.store') }}",
                    method: 'post',
                    data: {
                        name: $('#name').val(),
                        type: $('#type').val(),
                        website: $('#website').val(),
                        description: $('#description').val(),
                    },
                    success: function (result) {
                        if (result.success) {
                            $('.alert-danger').hide();
                            $('.datatable').DataTable().ajax.reload();
                            $('#name').val('');
                            $('#type').val('');
                            $('#website').val('');
                            $('#description').val('');
                            $('#CreateCompanyModal').modal('hide');
                        }
                    },
                    error: function (error) {
                        if (error.responseJSON && error.responseJSON.errors) {
                            $('.alert-danger').html('');
                            $.each(error.responseJSON.errors, function (key, value) {
                                $('.alert-danger').show();
                                $('.alert-danger').append('<strong><li>' + value + '</li></strong>');
                            });
                        }
                    }
                });
            });

            // Get single Company in EditModel
            $('.modelClose').on('click', function () {
                $('#EditCompanyModal').hide();
            });
            var id;
            $('body').on('click', '#getEditCompanyData', function (e) {
                e.preventDefault();
                $('.alert-danger').html('');
                $('.alert-danger').hide();
                id = $(this).data('id');
                $.ajax({
                    url: "companies/" + id + "/edit",
                    method: 'GET',
                    success: function (result) {
                        $('#EditCompanyModalBody').html(result.html);
                        $('#EditCompanyModal').show();
                    }
                });
            });

            // Update company Ajax request.
            $('#SubmitEditCompanyForm').click(function (e) {
                e.preventDefault();
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                $.ajax({
                    url: "companies/" + id,
                    method: 'PUT',
                    data: {
                        name: $('#editName').val(),
                        type: $('#editType').val(),
                        website: $('#editWebsite').val(),
                        description: $('#editDescription').val()
                    },
                    success: function (result) {
                        if (result.success) {
                            $('.edit-alert-danger').hide();
                            $('.datatable').DataTable().ajax.reload();
                            $('#EditCompanyModal').hide();
                        }
                    },
                    error: function (error) {
                        if (error.responseJSON && error.responseJSON.errors) {
                            $('.edit-alert-danger').html('');
                            $.each(error.responseJSON.errors, function (key, value) {
                                $('.edit-alert-danger').show();
                                $('.edit-alert-danger').append('<strong><li>' + value + '</li></strong>');
                            });
                        }
                    }
                });
            });

            // Delete company Ajax request.
            let deleteID;
            $('body').on('click', '#getDeleteId', function () {
                deleteID = $(this).data('id');
            })
            $('#SubmitDeleteCompanyForm').click(function (e) {
                e.preventDefault();
                let id = deleteID;
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                $.ajax({
                    url: "companies/" + id,
                    method: 'DELETE',
                    success: function (result) {
                        if (result.success) {
                            $('#DeleteCompanyModal').modal('hide');
                            $('.datatable').DataTable().ajax.reload();
                        }
                    }
                });
            });
        });
    </script>
@endsection

resources/views/employees/edit.blade.php
<div class="form-group">
    <label for="Name">First name*:</label>
    <input type="text" class="form-control" name="first_name" id="editFirstName" value="{{$employee->first_name}}">
</div>
<div class="form-group">
    <label for="Name">Last name*:</label>
    <input type="text" class="form-control" name="last_name" id="editLastName" value="{{$employee->last_name}}">
</div>
<div class="form-group">
    <label for="email">Email*:</label>
    <input type="text" class="form-control" name="email" id="editEmail" value="{{$employee->email_address}}">
</div>

<div class="form-group">
    <label for="Company">Company*:</label>
    <select class="form-control" name="company_id" id="editCompanyId">
        @foreach($companies as $company)
            <option value="{{$company->id}}" {{ ($employee->company_id ===  $company->id) ? 'selected' : ''}} >{{$company->name}}</option>
        @endforeach
    </select>
</div>
<div class="form-group">
    <label for="email">Position*:</label>
    <input type="text" class="form-control" name="position" id="editPosition" value="{{$employee->position}}">
</div>
<div class="form-group">
    <label for="email">City*:</label>
    <input type="text" class="form-control" name="city" id="editCity" value="{{$employee->city}}">
</div>
<div class="form-group">
    <label for="email">Country*:</label>
    <input type="text" class="form-control" name="country" id="editCountry" value="{{$employee->country}}">
</div>
<div class="form-group">
    <label for="Company">Status*:</label>
    <select class="form-control" name="status" id="editStatus">
        <option value="1" {{ $employee->status ? 'selected' : ''}}>Active</option>
        <option value="0" {{ !$employee->status ? 'selected' : ''}}>Inactive</option>
    </select>
</div>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Technical round</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet">
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
</head>
<body>
@yield('content')
</body>

@yield('script')
</html>